defmodule LineDrive.Incoming.DealHandlerTest do
  use ExUnit.Case, async: true

  alias LineDrive.Deal
  alias LineDrive.Incoming.DealHandler

  describe "deal_updated/1" do
    test "it transforms a well formed updated deal event into the correct event type and payload tuple" do
      example_webhook_body = %{
        "current" => %{
          "next_activity_type" => nil,
          "update_time" => "2022-07-21 03:19:21",
          "label" => nil,
          "title" => "Mecklem, LLC deal",
          "id" => 3,
          "renewal_type" => "one_time",
          "formatted_value" => "$50,010",
          "activities_count" => 0,
          "next_activity_id" => nil,
          "undone_activities_count" => 0,
          "status" => "open",
          "org_name" => "Mecklem, LLC",
          "deleted" => false,
          "next_activity_duration" => nil,
          "weighted_value" => 50_010,
          "done_activities_count" => 0,
          "last_outgoing_mail_time" => nil,
          "currency" => "USD",
          "cc_email" => "launchscout-sandbox+deal3@pipedrivemail.com",
          "person_id" => 1,
          "org_id" => 1,
          "lost_time" => nil,
          "next_activity_time" => nil,
          "probability" => nil,
          "participants_count" => 1,
          "group_name" => nil,
          "pipeline_id" => 2,
          "first_won_time" => nil,
          "last_incoming_mail_time" => nil,
          "followers_count" => 1,
          "email_messages_count" => 0,
          "org_hidden" => false,
          "last_activity_id" => nil,
          "files_count" => 0,
          "group_id" => nil,
          "stage_order_nr" => 1,
          "user_id" => 15_783_886,
          "lost_reason" => nil,
          "creator_user_id" => 15_783_886,
          "person_name" => "Tim Mecklem",
          "owner_name" => "Tim Mecklem",
          "formatted_weighted_value" => "$50,010",
          "stage_change_time" => nil,
          "close_time" => nil,
          "rotten_time" => nil,
          "products_count" => 0,
          "visible_to" => "3",
          "last_activity_date" => nil,
          "value" => 50_010,
          "expected_close_date" => nil,
          "active" => true,
          "person_hidden" => false,
          "next_activity_note" => nil,
          "next_activity_subject" => nil,
          "notes_count" => 0,
          "stage_id" => 7,
          "add_time" => "2022-07-19 02:26:59",
          "won_time" => nil,
          "weighted_value_currency" => "USD",
          "next_activity_date" => nil
        },
        "event" => "updated.deal",
        "matches_filters" => %{"current" => []},
        "meta" => %{
          "action" => "updated",
          "change_source" => "app",
          "company_id" => 11_796_774,
          "host" => "launchscout-sandbox.pipedrive.com",
          "id" => 3,
          "is_bulk_update" => false,
          "matches_filters" => %{"current" => []},
          "object" => "deal",
          "permitted_user_ids" => [9_452_636, 15_783_886, 15_820_406, 15_820_417],
          "pipedrive_service_name" => false,
          "timestamp" => 1_658_373_561,
          "timestamp_micro" => 1_658_373_561_109_302,
          "trans_pending" => false,
          "user_id" => 15_783_886,
          "v" => 1,
          "webhook_id" => "3831045"
        },
        "previous" => %{
          "next_activity_type" => nil,
          "update_time" => "2022-07-21 03:18:06",
          "label" => nil,
          "title" => "Mecklem, LLC deal",
          "id" => 3,
          "renewal_type" => "one_time",
          "formatted_value" => "$50,011",
          "activities_count" => 0,
          "next_activity_id" => nil,
          "undone_activities_count" => 0,
          "status" => "open",
          "org_name" => "Mecklem, LLC",
          "deleted" => false,
          "next_activity_duration" => nil,
          "weighted_value" => 50_011,
          "done_activities_count" => 0,
          "last_outgoing_mail_time" => nil,
          "currency" => "USD",
          "cc_email" => "launchscout-sandbox+deal3@pipedrivemail.com",
          "person_id" => 1,
          "org_id" => 1,
          "lost_time" => nil,
          "next_activity_time" => nil,
          "probability" => nil,
          "participants_count" => 1,
          "group_name" => nil,
          "pipeline_id" => 2,
          "first_won_time" => nil,
          "last_incoming_mail_time" => nil,
          "followers_count" => 1,
          "email_messages_count" => 0,
          "org_hidden" => false,
          "last_activity_id" => nil,
          "files_count" => 0,
          "group_id" => nil,
          "stage_order_nr" => 1,
          "user_id" => 15_783_886,
          "lost_reason" => nil,
          "creator_user_id" => 15_783_886,
          "person_name" => "Tim Mecklem",
          "owner_name" => "Tim Mecklem",
          "formatted_weighted_value" => "$50,011",
          "stage_change_time" => nil,
          "close_time" => nil,
          "rotten_time" => nil,
          "products_count" => 0,
          "visible_to" => "3",
          "last_activity_date" => nil,
          "value" => 50_011,
          "expected_close_date" => nil,
          "active" => true,
          "person_hidden" => false,
          "next_activity_note" => nil,
          "next_activity_subject" => nil,
          "notes_count" => 0,
          "stage_id" => 7,
          "add_time" => "2022-07-19 02:26:59",
          "won_time" => nil,
          "weighted_value_currency" => "USD",
          "next_activity_date" => nil
        },
        "retry" => 0,
        "v" => 1
      }

      assert {:updated_deal,
              %{
                current: %Deal{
                  id: 3,
                  weighted_value: 50_010,
                  expected_close_date: nil,
                  pipeline_id: 2,
                  stage_id: 7,
                  status: "open",
                  title: "Mecklem, LLC deal",
                  value: 50_010
                },
                meta: %{"host" => "launchscout-sandbox.pipedrive.com"},
                previous: %Deal{
                  id: 3,
                  weighted_value: 50_011,
                  expected_close_date: nil,
                  pipeline_id: 2,
                  stage_id: 7,
                  status: "open",
                  title: "Mecklem, LLC deal",
                  value: 50_011
                }
              }} = DealHandler.deal_updated(example_webhook_body)
    end
  end
end
